version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: database
    command:
      - "--authentication_policy=mysql_native_password"
    environment:
      MYSQL_DATABASE: datatestdb
      MYSQL_USER: datatest
      MYSQL_PASSWORD: alligator
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-schemas:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: on-failure
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 20
      start_period: 30s

  assessment:
    build: .
    container_name: assessment
    command: [ "python", "run.py" ]
    volumes:
      - ./data:/data
      - ./assessment:/assessment
    depends_on:
      database:
        condition: service_healthy

  test:
    build: .
    container_name: test
    command: [ "python", "test.py" ]
    # command: [ "tail", "-F", "whatever" ]
    volumes:
      - ./assessment:/assessment
    depends_on:
      database:
        condition: service_healthy
